WebProject/WebProject/Controllers/WriterController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Security.Claims;
using BusinessLayer.Concrete;
using BusinessLayer.ValidationRules;
using DataAccessLayer.EntityFramework;
using EntityLayer.Concrete;
using FluentValidation.Results;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using WebProject.Base;
using WebProject.Models;

namespace WebProject.Controllers
{

    public class WriterController : BaseController
    {
        WriterManager wm = new WriterManager(new EfWriterRepository());
        public PartialViewResult WriterNavbarPartial()
        {
            return PartialView();
        }
        public PartialViewResult WriterFooterPartial()
        {
            return PartialView();
        } 
        public Writer FindBy()
        {
            //Base dosyasında bulunduğumuz Writer ın id sini yönlendiren kodu yazdık Id bizim bulunduğumuz WriterId
            return wm.GetById(Id);
        }

        [HttpGet]
        public IActionResult WriterEditProfile()
        {
            SelectCities();
            //var id = Convert.ToInt32(((ClaimsIdentity)User.Identity)?.FindFirst(ClaimTypes.Name)?.Value);
            return View(FindBy()); 
        } 

       
        [HttpPost]
        public IActionResult WriterEditProfile(Writer writer, string confirmPassword, IFormFile WriterImage)
        {
            WriterValidator writerValidator = new WriterValidator();
            ValidationResult validation = writerValidator.Validate(writer);
            if (validation.IsValid && writer.WriterPassword == confirmPassword)
            {
                if (WriterImage != null)
                {
                    Models.FormFile file = new Models.FormFile();
                    writer.WriterImage = file.UpdatedFile(WriterImage, FindBy().WriterImage); //ikinci parametre olarak bulunduğumuz kullanıcının id sini veriyoruz bu bizim eski Image imiz
                }

                writer.WriterStatus = true;
                wm.TUpdate(writer);
                HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
                return RedirectToAction("Index","Login");
            }
            else
            {
                if (writer.WriterPassword == confirmPassword)
                    ViewBag.Problem = "Passwords not match";

                foreach (var item in validation.Errors)
                {
                    ModelState.AddModelError(item.PropertyName, item.ErrorMessage);
                }
            }

            SelectCities();
            return View(writer);
        }

        public void SelectCities()
        {
            String[] citiesArray = { "Adana", "Adıyaman", "Afyon", "Ağrı", "Aksaray", "Amasya", "Ankara", "Antalya", "Ardahan", "Artvin", "Aydın", "Bartın", "Batman", "Balıkesir", "Bayburt", "Bilecik", "Bingöl", "Bitlis", "Bolu", "Burdur", "Bursa", "Çanakkale", "Çankırı", "Çorum", "Denizli", "Diyarbakır", "Düzce", "Edirne", "Elazığ", "Erzincan", "Erzurum", "Eskişehir", "Gaziantep", "Giresun", "Gümüşhane", "Hakkari", "Hatay", "Iğdır", "Isparta", "İçel", "İstanbul", "İzmir", "Karabük", "Karaman", "Kars", "Kastamonu", "Kayseri", "Kırıkkale", "Kırklareli", "Kırşehir", "Kilis", "Kocaeli", "Konya", "Kütahya", "Malatya", "Manisa", "Kahramanmaraş", "Mardin", "Muğla", "Muş", "Nevşehir", "Niğde", "Ordu", "Osmaniye", "Rize", "Sakarya", "Samsun", "Siirt", "Sinop", "Sivas", "Tekirdağ", "Tokat", "Trabzon", "Tunceli", "Şanlıurfa", "Şırnak", "Uşak", "Van", "Yalova", "Yozgat", "Zonguldak" };
            List<SelectListItem> cities = (from x in citiesArray
                                           select new SelectListItem
                                           {
                                               Text = x,
                                               Value = x
                                           }).ToList();
            ViewBag.Cities = cities;
        }


    }
}

WebProject/WebProject/Views/Writer/Index.cshtml
@{
    Layout = null;
}

WebProject/WebProject/Views/Writer/WriterEditProfile.cshtml
@model EntityLayer.Concrete.Writer
@{
    ViewData["Title"] = "WriterEditProfile";
    Layout = "~/Views/Shared/WriterLayout.cshtml";
}

@using (Html.BeginForm("WriterEditProfile", "Writer", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <div class="col-12 grid-margin stretch-card">
        <div class="card">
            <div class="card-body">
                <h4 class="card-title">Writer Edit</h4>
                <br />

                <form class="forms-sample">
                    <input asp-for="WriterId" type="hidden" />

                    <div class="form-group">
                        <label for="exampleInputName1">Name</label>
                        @Html.TextBoxFor(x => x.WriterName, new { @class = "form-control" })
                        @Html.ValidationMessageFor(x => x.WriterName)
                    </div>
                    <div class="form-group">
                        <label for="exampleInputEmail3">Email</label>
                        @Html.TextBoxFor(x => x.WriterMail, new { @class = "form-control" })
                        @Html.ValidationMessageFor(x => x.WriterMail)
                    </div>
                    <div class="form-group">
                        @Html.DropDownListFor(x => x.WriterCity, (List<SelectListItem>)ViewBag.Cities, new { @class = "form-control dropdown" })
                    </div>
                    <div class="form-group">
                        <label for="exampleInputPassword4">Password</label>
                        @Html.PasswordFor(x => x.WriterPassword, new { @class = "form-control" })
                        @Html.ValidationMessageFor(x => x.WriterPassword, "", new { @class = "text-danger" })
                    </div>
                    <div class="form-group">
                        <label for="exampleInputPassword2 mb-2">Confirm Password</label>
                        <input type="password" name="confirmPassword" class="form-control" id="password2" placeholder="Please input again" required="" />
                    </div>
                    <div class="form-group">
                        <label>Your Image</label>
                        <input type="file" name="WriterImage" class="form-control" />
                    </div>
                    <div class="form-group">
                        <label for="exampleTextarea1">About</label>
                        @Html.TextAreaFor(x => x.WriterAbout,new { @id = "editor1" })
                        @Html.ValidationMessageFor(x => x.WriterAbout)
                    </div>
                    <button type="submit" class="btn btn-gradient-primary mr-2">Update</button>

                </form>
            </div>
        </div>
    </div>

    <script src="~/ckeditor/ckeditor.js"></script>
    <script>
        CKEDITOR.replace('editor1');
    </script>

}

WebProject/WebProject/Views/Writer/WriterFooterPartial.cshtml
<footer class="footer">
    <div class="container-fluid clearfix">
        <span class="text-muted d-block text-center text-sm-left d-sm-inline-block">Copyright © Escan Dönmez | @DateTime.Now.Year</span>
    </div>
</footer>

WebProject/WebProject/Views/Writer/WriterNavbarPartial.cshtml
<nav class="sidebar sidebar-offcanvas" id="sidebar">
    <ul class="nav">
        @await Component.InvokeAsync("WriterProfileMini")
        <li class="nav-item active  ">
            <a class="nav-link" href="/Dashboard/Index/">
                <span class="menu-title">Dashboard</span>
                <i class="mdi mdi-home menu-icon"></i>
            </a>
        </li>

        <li class="nav-item">
            <a class="nav-link" href="~/writer/pages/icons/mdi.html">
                <span class="menu-title">Profile</span>
                <i class="mdi mdi-contacts menu-icon"></i>
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="~/Blog/BlogListByWriter">
                <span class="menu-title">My Blogs</span>
                <i class="mdi mdi-format-list-bulleted menu-icon"></i>
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="~/Blog/BlogAdd">
                <span class="menu-title">New Blog</span>
                <i class="mdi mdi-new-box menu-icon"></i>
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="~/Messages2/Index">
                <span class="menu-title">Messages</span>
                <i class="mdi mdi-message menu-icon"></i>
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="/Notification/AllNotification">
                <span class="menu-title">Notifications</span>
                <i class="mdi mdi-bell menu-icon"></i>
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="~/Blog/Index">
                <span class="menu-title">Visit Site</span>
                <i class="mdi mdi-car menu-icon"></i>
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="~/Writer/WriterEditProfile/">
                <span class="menu-title">Settings</span>
                <i class="mdi mdi-settings menu-icon"></i>
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="~/Login/LogOut">
                <span class="menu-title">Log Out</span>
                <i class="mdi mdi-logout menu-icon"></i>
            </a>
        </li>
    </ul>
</nav>

WebProject/WebProject/Views/Writer/WriterProfile.cshtml
@{
    Layout = null;
}